### ISSUE TITLE
Error while doing make

### ISSUE THREAD

**Issue by tenshioopai** [kuba-moo/mt7601u#10]
Helle there,

I've been trying to install my nameless usb dongle to work on my raspberry pi  for quite some but with no success. Today I tried your method and get an error while trying to do make.
![errorduringmake](https://cloud.githubusercontent.com/assets/9588962/6993168/58d9ce1a-daec-11e4-9173-57a6999a3c3e.PNG)
Could you help me with this. Raspbery Pi and Linux itself is still pretty new for me.

**Comment by ghost** [comment]
This driver works only with kernel 3.19 and newer. You are trying to build it with 3.10 headers.

**Comment by tenshioopai** [comment]
Ohh, of course! I should have seen that! Thank you!

**Comment by kuba-moo** [comment]
Thanks!
