### ISSUE TITLE
Need Linux Headers

### ISSUE THREAD

**Issue by tfcarlin** [kuba-moo/mt7601u#11]
My first attempt to make the driver resulted in the error:

root@arm:~/mt7601u# make
make -C /lib/modules/`uname -r`/build M=$PWD
make: **\* /lib/modules/3.19.3-bone4/build: No such file or directory.  Stop.
make: **\* [default] Error 2

Installing linux headers corrected this problem:

apt-get install linux-headers-$(uname -r)

**Comment by kuba-moo** [comment]
Thanks for the report, I added something to README but I'm not sure if it's clear...
