### ISSUE TITLE
More MT7601U devices

### ISSUE THREAD

**Issue by xosevp** [kuba-moo/mt7601u#17]
Taken from latest Windows driver (12/11/2014, 5.01.20.0000)

(0x0b05, 0x17d3) ASUS USB-N10 150Mbps 11n Wireless USB dongle
(0x0e8d, 0x760a) Treebear Traffic Radar
(0x0e8d, 0x760b) Ogemray
(0x13d3, 0x3431) AzureWave
(0x13d3, 0x3434) AzureWave
(0x148f, 0x760a) Ralink
(0x148f, 0x760c) Ralink
(0x148f, 0x760d) Ralink
(0x2001, 0x3d04) D-Link DWA-127/B1 Wireless N 150 High-Gain USB Adapter
(0x7392, 0x7710) Edimax N150 Wireless USB Adapter

**Comment by kuba-moo** [comment]
Can you send me a patch? ;)

**Comment by xosevp** [comment]
Done.
