### ISSUE TITLE
Working good

### ISSUE THREAD

**Issue by R3DDY97** [kuba-moo/mt7601u#32]
Thanks for the developers for this drive
its working for Wayona WYN 12 150Mbps 1T1R 2.4Ghz 802.11n/g/b Soft AP Wireless Mini USB Wifi Adapter

Serched many sites for 2 days without sleeping to fix it in Kali linux 2.
FInally this driver helped a lot
Im relieved

**Comment by kuba-moo** [comment]
You're welcome. Hope it still works for you :)
