### ISSUE TITLE
Possibility around multiple virtual interfaces / BSSID

### ISSUE THREAD

**Issue by cusspvz** [kuba-moo/mt7601u#43]
Does this driver support, or is it possible to have, multiple BSSID configuration on mt7601u?

One of my needs is to have 3 bssid to connect to different networks on the same channel.
## 

Thanks,
José Moreira

**Comment by kuba-moo** [comment]
I don't think HW is designed to do that, unfortunately. IIRC there is only one set of BSSID registers, also Ralink devices with have very similar MAC never supported multiple STAs...
