### ISSUE TITLE
Cross Compiling error

### ISSUE THREAD

**Issue by SandeshKa07** [kuba-moo/mt7601u#45]
I am using beaglebone, rootfile system is in my host system. I am using linux 4.1 source and when i run make command in the target console it gave the error 
/bin/sh: ./scripts/recordmcount: cannot execute binary file

Please someone help me out with this

**Comment by kuba-moo** [comment]
I'm sorry but this is not in any way related to this driver. It's a general cross-compilation issue. I can't help you.
