### ISSUE TITLE
Error: RX path seen a non-pkt urb

### ISSUE THREAD

**Issue by clivem** [kuba-moo/mt7601u#47]
Not sure if you are interested in this here, or whether I should report upstream?

[mt7601u_non-pkt.txt](https://github.com/kuba-moo/mt7601u/files/92455/mt7601u_non-pkt.txt)

**Comment by kuba-moo** [comment]
Quite surprising. No need to report upstream, nobody will care over there ;)

Can you reproduce this easily or was it a one time thing? What device is it?

**Comment by clivem** [comment]
Sorry, was expecting an email notification if I got a reply, didn't get notified that you had responded....

Anyway, I've not seen it since, so I doubt it is very easily reproduced. I'll close this report and re-open if I ever see it again.
