### ISSUE TITLE
Unable to compile: No such file or directory

### ISSUE THREAD

**Issue by Sam-Izdat** [kuba-moo/mt7601u#5]
Maybe I'm missing something obvious...

```
$ make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory `/usr/src/linux-headers-3.19.0-031900-generic'
make[1]: Makefile: No such file or directory
make[1]: *** No rule to make target `Makefile'.  Stop.
make[1]: Leaving directory `/usr/src/linux-headers-3.19.0-031900-generic'
make: *** [default] Error 2

$ ls /lib/firmware/ | grep mt7601u
mt7601u.bin

$ ls /usr/src/ | grep linux-headers-3.19.0-031900-generic
linux-headers-3.19.0-031900-generic

$ uname -r
3.19.0-031900-generic

$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

I wish I could say more, but I'm really not even sure what's happening.

**Comment by kuba-moo** [comment]
Do you have linux-headers installed? Is there anything inside /usr/src/linux-headers-3.19.0-031900-generic?

**Comment by Sam-Izdat** [comment]
Upon inspecting further, I think you're right and the problem is the linux headers. After upgrading, `make` can't compile much of anything. I'll try to upgrade to a different kernel, check that the headers are there and report back.

edit: Okay, I'm struggling to get this Ubuntu release to play nice with anything higher than the stock kernel, but I'm reasonably sure that the problem had nothing to do with this driver specifically, so I'll close the issue. Apologies.
