### ISSUE TITLE
How to build a kernel module for 3.10.0-327.3.1.el7.x86_64

### ISSUE THREAD

**Issue by wmlex** [kuba-moo/mt7601u#50]
When you try to compile the module displays the following error:

make
make -C /lib/modules/`uname -r`/build M=$PWD

make[1]: Вход в каталог `/usr/src/kernels/3.10.0-327.3.1.el7.x86_64'
  LD      /root/mt7601u-master/built-in.o
  CC [M]  /root/mt7601u-master/usb.o
  CC [M]  /root/mt7601u-master/init.o

/root/mt7601u-master/init.c: В функции «mt76_init_sband»:
/root/mt7601u-master/init.c:533:2: ошибка: неявная декларация функции «devm_kmemdup» [-Werror=implicit-function-declaration]
  chanlist = devm_kmemdup(dev->dev, chan, size, GFP_KERNEL);
  ^
/root/mt7601u-master/init.c:533:11: ошибка: в присваивании целое преобразуется в указатель без приведения типа [-Werror]
  chanlist = devm_kmemdup(dev->dev, chan, size, GFP_KERNEL);
           ^
cc1: all warnings being treated as errors
make[2]: **\* [/root/mt7601u-master/init.o] Ошибка 1
make[1]: **\* [_module_/root/mt7601u-master] Ошибка 2
make[1]: Выход из каталога `/usr/src/kernels/3.10.0-327.3.1.el7.x86_64'
make: **\* [default] Ошибка 2

**Comment by kuba-moo** [comment]
As stated in README:
`To use this driver you need to upgrade your kernel to at least Linux 3.19.`

I guess you could try latest backport drivers if you want to stick to RHEL:
https://backports.wiki.kernel.org/index.php/Main_Page
This driver should be included there.
