### ISSUE TITLE
mt7601u/mt7601u.h:166:27: error: field ‘chandef’ has incomplete type

### ISSUE THREAD

**Issue by npasparuhov** [kuba-moo/mt7601u#51]
When i try to make it that error appears: 
mt7601u/mt7601u.h:166:27: error: field ‘chandef’ has incomplete type
I'm using kernel 3.4.110 on Orange Pi PC and the build output is:
In file included from /root/mt7601u/usb.c:18:0:
/root/mt7601u/mt7601u.h:166:27: error: field ‘chandef’ has incomplete type
  struct cfg80211_chan_def chandef;
                           ^
/root/mt7601u/mt7601u.h:273:14: error: ‘IEEE80211_NUM_TIDS’ undeclared here (not in a function)
  u16 agg_ssn[IEEE80211_NUM_TIDS];
              ^
/root/mt7601u/mt7601u.h:373:10: error: ‘struct ieee80211_tx_control’ declared inside parameter list [-Werror]
   struct sk_buff *skb);
          ^
/root/mt7601u/mt7601u.h:373:10: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
/root/mt7601u/usb.c: In function ‘mt7601u_probe’:
/root/mt7601u/usb.c:267:2: error: implicit declaration of function ‘devm_kmalloc’ [-Werror=implicit-function-declaration]
  dev->vend_buf = devm_kmalloc(dev->dev, MT_VEND_BUF, GFP_KERNEL);
And so on.
Can u help me to compile that driver cuz i really need it.
Thanks for the help!

**Comment by kuba-moo** [comment]
Thanks for the report but you're using unsupported kernel version. As it's stated on the README - you need at least 3.19.
