### ISSUE TITLE
The phy physic ra0 not detect after driver instaled

### ISSUE THREAD

**Issue by dimastt** [kuba-moo/mt7601u#52]
I just use a WifiSlax4.11.1 on vbox host win7 and after instaled driver ra0 dont get a phy physic with iw. dev command.
get output with: lsmod - mt7601Usta
                          dmesg - register new interface driver rt2870
                          iwconfig - ra0.......

If possible help for make active phisic phy card
thanks.

**Comment by kuba-moo** [comment]
How did you install the driver?
This repository does not contain mt7601Usta driver.
