### ISSUE TITLE
Github link in README is no longer valid

### ISSUE THREAD

**Issue by fossum** [kuba-moo/mt7601u#54]
The very last link in the README is no longer valid and needs to be updated.

"like this one: https://github.com/porjo/mt7601"

**Comment by wilberforce** [comment]
There is a reference to the firmware here:

https://github.com/RPi-Distro/firmware-nonfree/commit/cff948c481bfd593492b7ebc804d8db21d7c237c

@kuba-moo is this the correct bin file?

**Comment by kuba-moo** [comment]
Fixed!

@wilberforce (a) don't post unrelated questions in issues, please :wink:  (b) yes, that file looks OK!
