### ISSUE TITLE
Support for TP-Link Archer T1U idVendor=2357 idProduct=0105 with modern kernel

### ISSUE THREAD

**Issue by CalebCarroll** [kuba-moo/mt7601u#62]
I'm running kernel 4.9.13 at the moment and have tried adding support for the 802.11ac USB adapter by adding the following to mt7601u.mod.c:
MODULE_ALIAS("usb:v2357p0105d\*dc\*dsc\*dp\*ic\*isc\*ip\*in*");
and usb.c:
{ USB_DEVICE(0x2357, 0x0105) }

It seems to have almost worked.  The USB adapter's indicator light comes on and certain aspects of the device is being recognized:

[  373.749011] usbcore: registered new interface driver mt7601u
[  374.998706] usb 1-1.4: new high-speed USB device number 6 using dwc_otg
[  375.144335] usb 1-1.4: New USB device found, idVendor=2357, idProduct=0105
[  375.144348] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  375.144356] usb 1-1.4: Product: WiFi
[  375.144364] usb 1-1.4: Manufacturer: MediaTek
[  375.144371] usb 1-1.4: SerialNumber: 1.0
[  375.238706] usb 1-1.4: reset high-speed USB device number 6 using dwc_otg
[  375.373686] mt7601u 1-1.4:1.0: ASIC revision: 76100002 MAC revision: 76502000
[  375.375108] mt7601u 1-1.4:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[  730.070528] mt7601u 1-1.4:1.0: Vendor request req:02 off:0080 failed:-110
.
[  719.820475] mt7601u 1-1.4:1.0: Vendor request req:07 off:0730 failed:-110
[  723.270498] mt7601u 1-1.4:1.0: Vendor request req:07 off:0080 failed:-110
[  726.670532] mt7601u 1-1.4:1.0: Vendor request req:02 off:0080 failed:-110
[  730.070528] mt7601u 1-1.4:1.0: Vendor request req:02 off:0080 failed:-110

Unfortunately, I'm not a firmware guy so I'll be returning this adapter to the store tomorrow.  I'm just posting what I've tried & observed in case someone's interested in updating this kernel module to work with newer USB WiFi devices and newer kernels.

**Comment by kuba-moo** [comment]
It's a MT7610, not MT7601 chip so this driver would require significant work to support it.  Sorry :(
