### ISSUE TITLE
MT7610

### ISSUE THREAD

**Issue by MJavad** [kuba-moo/mt7601u#63]
Hi,
I need a working mac80211 driver for mt7610 and I found your project is the best one to start from.
I've never coded any driver stuff, but I've got enough free time to get started.
So i'm asking if you could help me. I need some pointers so I can start development.

**Comment by kuba-moo** [comment]
Hi there!
A bit of a general question you ask ;)  The way I learned was by reading other people's code and linux-wireless mailing list...  I'm afraid there is no simple starting guide that I know of :(
Good luck!
