### ISSUE TITLE
Problem with key in Archer T2U

### ISSUE THREAD

**Issue by IbaiIR** [kuba-moo/mt7601u#65]
Hi,
I've been trying to connect to a WPA2PSK/AES encrypted network and it doesn't work. I've followed this steps:
iwpriv ra0 set NetworkType=Infra
iwpriv ra0 set AuthMode=WPA2PSK
iwpriv ra0 set EncrypType=AES
iwpriv ra0 set SSID="mugikorra"
iwpriv ra0 set WPAPSK="12345678"
iwpriv ra0 set SSID="mugikorra"

and this is what it turns:

Ralink STA ESSID:"mugikorra" Nickname:"MT7610U_STA"
Mode:Auto Frequency=2.462 GHz Access Point: Not-Associated
Bit Rate:1 Mb/s
RTS thr:off Fragment thr:off
Encryption key:off
Link Quality=88/100 Signal level:-45 dBm Noise level:-45 dBm
Rx invalid nwid:0 Rx invalid crypt:0 Rx invalid frag:0
Tx excessive retries:0 Invalid misc:0 Missed beacon:0

If I connect to an open network it works perfectly. I follow this steps:

iwpriv ra0 set NetworkType=Infra
iwpriv ra0 set AuthMode=OPEN
iwpriv ra0 set EncrypType=NONE
iwpriv ra0 set SSID="mugikorra"

And this is what I get back:

Ralink STA ESSID:"mugikorra" Nickname:"MT7610U_STA"
Mode:Managed Frequency=2.437 GHz Access Point: B4:9D:0B:5C:08:52
Bit Rate=65 Mb/s
RTS thr:off Fragment thr:off
Encryption key:off
Link Quality=100/100 Signal level:-26 dBm Noise level:-55 dBm
Rx invalid nwid:0 Rx invalid crypt:0 Rx invalid frag:0
Tx excessive retries:0 Invalid misc:0 Missed beacon:0

Any ideas? Thank you very much!

**Comment by kuba-moo** [comment]
This has nothing to do with the `mt7601u` driver.
