### ISSUE TITLE
Can't read private key

### ISSUE THREAD

**Issue by xxsong5** [kuba-moo/mt7601u#68]
xxsong5@xxsong5:~/mt7601u$ sudo make install
make -C /lib/modules/`uname -r`/build M=$PWD modules_install
make[1]: Entering directory `/usr/src/linux-headers-3.19.0-80-generic'
  INSTALL /home/xxsong5/mt7601u/mt7601u.ko
Can't read private key
  DEPMOD  3.19.0-80-generic
make[1]: Leaving directory `/usr/src/linux-headers-3.19.0-80-generic'

**Comment by jeremyb31** [comment]
Go into BIOS and disable Secure Boot

**Comment by kuba-moo** [comment]
This is not an issue with this driver.  Just google "*Can't read private key*" you will find out what's going on.
