### ISSUE TITLE
not working for Baidu mini wifi and Tencent mini wifi

### ISSUE THREAD

**Issue by whitehamster** [kuba-moo/mt7601u#7]
There are two devices which like Xiaomi mini wifi from China.
I'm sure they are mt7601u devices
Baidu mini wifi:
Bus 001 Device 011: ID 2955:1001
Tencent mini wifi:
Bus 001 Device 013: ID 2a5f:1000
Add support for them please;-)
Sorry for my poor english....

**Comment by whitehamster** [comment]
More device ID
{USB_DEVICE(0x148f,0x760b)}, /\* 360 Wifi _/
{USB_DEVICE(0x2955,0x1001)}, /_ baidu Wifi _/
{USB_DEVICE(0x2a5f,0x1000)}, /_ Tencent WIFI _/
{USB_DEVICE(0×2955,0×0001)}, /_ XiaoDu Wifi _/
{USB_DEVICE(0x2717,0x4106)}, /_ Xiaomi Wifi */

From [there](http://shumeipai.nxez.com/2014/12/07/raspberry-pi-use-360wifi.html)

**Comment by kuba-moo** [comment]
Done, thanks for the report :)

**Comment by whitehamster** [comment]
Thank you :-)
