### ISSUE TITLE
error while installing on  Ubuntu 4.10.0

### ISSUE THREAD

**Issue by WayneWZ** [kuba-moo/mt7601u#73]
root@ute572-2:/opt/software/mt7601u-master# uname -a
Linux ute572-2 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@ute572-2:/opt/software/mt7601u-master# make install
make -C /lib/modules/`uname -r`/build M=$PWD modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-19-generic'
  INSTALL /opt/software/mt7601u-master/mt7601u.ko
At main.c:158:
**- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178**
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.10.0-19-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-19-generic'
root@ute572-2:/opt/software/mt7601u-master#

**Comment by kuba-moo** [comment]
You don't have the key to sign the module.
