### ISSUE TITLE
kernel  4.0.15 ，insmod 出现下面错误

### ISSUE THREAD

**Issue by Clssrie** [kuba-moo/mt7601u#86]
[   86.812115] mt7601u: disagrees about version of symbol module_layout
[  314.363365] usb 1-1: USB disconnect, device number 4
[  314.368570] mt7601u: probe of 1-1:1.0 failed with error -5
[  314.378700] usbcore: registered new interface driver mt7601u
[  314.493142] usb 1-1: new full-speed USB device number 5 using ci_hdrc
[  314.733284] usb 1-1: new full-speed USB device number 6 using ci_hdrc
[  314.973373] usb 1-1: new full-speed USB device number 7 using ci_hdrc
[  315.007776] usb 1-1: No LPM exit latency info found, disabling LPM.
[  315.014773] usb 1-1: not running at top speed; connect to a high speed hub
[  315.173413] mt7601u: probe of 1-1:1.0 failed with error -5
[  315.181230] usb 1-1: USB disconnect, device number 7
[  315.303150] usb 1-1: new full-speed USB device number 8 using ci_hdrc
[  315.543259] usb 1-1: new full-speed USB device number 9 using ci_hdrc
[  315.783199] usb 1-1: new full-speed USB device number 10 using ci_hdrc
[  315.817773] usb 1-1: No LPM exit latency info found, disabling LPM.
[  315.824764] usb 1-1: not running at top speed; connect to a high speed hub
[  315.983497] mt7601u: probe of 1-1:1.0 failed with error -5
[  315.991399] usb 1-1: USB disconnect, device number 10
[  316.113148] usb 1-1: new full-speed USB device number 11 using ci_hdrc
[  316.353250] usb 1-1: new full-speed USB device number 12 using ci_hdrc
[  316.593424] usb 1-1: new full-speed USB device number 13 using ci_hdrc
[  316.627777] usb 1-1: No LPM exit latency info found, disabling LPM.
[  316.634765] usb 1-1: not running at top speed; connect to a high speed hub
[  316.793395] mt7601u: probe of 1-1:1.0 failed with error -5
[  316.801540] usb 1-1: USB disconnect, device number 13
[  316.923155] usb 1-1: new full-speed USB device number 14 using ci_hdrc
[  317.163324] usb 1-1: new full-speed USB device number 15 using ci_hdrc
[  317.403308] usb 1-1: new high-speed USB device number 16 using ci_hdrc
[  317.583174] usb 1-1: reset high-speed USB device number 16 using ci_hdrc
[  317.737413] mt7601u 1-1:1.0: ASIC revision: 76010001 MAC revision: 76010500
[  317.819970] mt7601u 1-1:1.0: Warning: unsupported EEPROM version 0d
[  317.826358] mt7601u 1-1:1.0: EEPROM ver:0d fae:00
[  318.078363] ieee80211 phy4: Selected rate control algorithm 'minstrel_ht'
[  318.408833] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready

**Comment by kuba-moo** [comment]
Not enough info to investigate this.
