### ISSUE TITLE
Android Kernel Crash

### ISSUE THREAD

**Issue by rustzz** [kuba-moo/mt7601u#91]
I manually compiled the kernel with the MT7601U module.
I connect the adapter, work with it, disconnect it and the smartphone goes into a hard restart.
/proc/kmsg: https://pastebin.com/6abgZDjB
Kernel [v4.9.112]: https://github.com/nikp123/Xiaomi_Kernel_OpenSource/tree/pine64-p-oss

Maybe it null-pointer: https://forum.keenetic.net/topic/4121-unable-to-handle-kernel-paging-request-at-virtual-address-00000000/

**Comment by kuba-moo** [comment]
It crashed in:
> PC is at hdd_netdev_notifier_call+0x74/0x11c [wlan]

That must be some Android thing, I don't see this function in the upstream kernel.

**Comment by rustzz** [comment]
https://github.com/torvalds/linux/commit/0acb20a5438c36e0cf2b8bf255f314b59fcca6ef
https://bugzilla.kernel.org/show_bug.cgi?id=210857

I found a discussion of the problem on the forum.
the fix was attached in new versions, now I will compile the kernel with the change and give an answer
